# SPRING --------------------------------------------------------------------------------------
spring:
  main:
    allow-bean-definition-overriding: true
  liquibase:
    enabled: false
  jpa:
    show-sql: true
eureka:
  instance:
    hostname: localhost
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registerWithEureka: true
    fetchRegistry: true

internal.apigate.services:
  user:
    name: PHONG-USER-SERVICE
  cert:
    name : PHONG-CERT-SERVICE
# CACHING --------------------------------------------------------------------------------------
cache.redis:
  host: 127.0.0.1
  port: 6379
feign:
  client:
    config:
      default:
        connectTimeout: 30000
        readTimeout: 30000
        loggerLevel: FULL