spring:
  # DATASOURCE
  datasource:
    url: jdbc:mysql://localhost:3306/data_test_api2?useUnicode=yes&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true&allowPublicKeyRetrieval=true
    username: phong
    password: Phamphong1
  liquibase:
    enabled: false
  main:
    allow-bean-definition-overriding: true